# Generated by Django 3.2.5 on 2021-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0009_auto_20210817_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='БытовыеТехники',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('пылесосы', 'Пылесосы'), ('стиральные машины', 'Стиральные машины'), ('холодильники', 'Холодильники')], default='xiaomi', max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='КлиматическаяТехника',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ноутбуки', 'Ноутбуки'), ('моноболки', 'Моноболки'), ('мониторы', 'Мониторы')], default='xiaomi', max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='КомпьютернаяТехника',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('вентиляторы', 'Вентиляторы'), ('кондиционеры', 'Кондиционеры'), ('обогреватели', 'Обогреватели')], default='xiaomi', max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='МужскиеТуфли',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[], default='xiaomi', max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='СпортивныеТовары',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[], default='xiaomi', max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='TV',
            new_name='Телевизоры',
        ),
        migrations.RenameModel(
            old_name='Telefon',
            new_name='Телефоны',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('бытовые-техники', 'Бытовые-техники'), ('компьютерная-техника', 'Компьютерная-техника'), ('климатическая-техника', 'Климатическая-техника'), ('спортивные-товары', 'Спортивные-товары'), ('мужские-туфли', 'Мужские-туфли'), ('телефоны', 'Телефоны'), ('телевизоры', 'Телевизоры')], default='xiaomi', max_length=300),
        ),
    ]