# Generated by Django 3.2.5 on 2021-08-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0010_auto_20210817_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='БытовыеТехники',
            new_name='BytovyeTexniki',
        ),
        migrations.RenameModel(
            old_name='КлиматическаяТехника',
            new_name='KlimaticheskayaTexnika',
        ),
        migrations.RenameModel(
            old_name='КомпьютернаяТехника',
            new_name='KomputernayaTexnika',
        ),
        migrations.RenameModel(
            old_name='СпортивныеТовары',
            new_name='MujskieTufli',
        ),
        migrations.RenameModel(
            old_name='МужскиеТуфли',
            new_name='SportivnyeTovary',
        ),
        migrations.RenameModel(
            old_name='Телефоны',
            new_name='Telefon',
        ),
        migrations.RenameModel(
            old_name='Телевизоры',
            new_name='Televizory',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bytovyetexniki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bytovyetexniki'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='klimaticheskayatexnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.klimaticheskayatexnika'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='komputernayatexnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.komputernayatexnika'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mujskietufli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.mujskietufli'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sportivnyetovary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sportivnyetovary'),
        ),
    ]