# Generated by Django 3.2.5 on 2021-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0015_alter_bytovyetexniki_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KomputernayaTexnika',
            new_name='Komputernaya',
        ),
    ]