# Generated by Django 3.2.5 on 2021-08-20 14:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0016_rename_komputernayatexnika_komputernaya'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komputernaya',
            new_name='KomputernayaTexnika',
        ),
    ]