# Generated by Django 3.2.5 on 2021-08-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0017_rename_komputernaya_komputernayatexnika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komputernaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('вентиляторы', 'Вентиляторы'), ('кондиционеры', 'Кондиционеры'), ('обогреватели', 'Обогреватели')], max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='komputernayatexnika',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.komputernaya'),
        ),
        migrations.DeleteModel(
            name='KomputernayaTexnika',
        ),
    ]