# Generated by Django 3.2.5 on 2021-08-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0019_rename_komputernaya_komputernayatexnika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klimaticheskayatexnika',
            name='category',
            field=models.CharField(choices=[('noutbuki', 'Ноутбуки'), ('monobolki', 'Моноболки'), ('monitory', 'Мониторы')], default='xiaomi', max_length=300),
        ),
        migrations.AlterField(
            model_name='komputernayatexnika',
            name='category',
            field=models.CharField(choices=[('ventilyatory', 'Вентиляторы'), ('konditsionery', 'Кондиционеры'), ('obogrevateli', 'Обогреватели')], max_length=300),
        ),
    ]