# Generated by Django 3.2.5 on 2021-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0020_auto_20210820_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klimaticheskayatexnika',
            name='category',
            field=models.CharField(choices=[('ventilyatory', 'Вентиляторы'), ('konditsionery', 'Кондиционеры'), ('obogrevateli', 'Обогреватели')], default='xiaomi', max_length=300),
        ),
        migrations.AlterField(
            model_name='komputernayatexnika',
            name='category',
            field=models.CharField(choices=[('noutbuki', 'Ноутбуки'), ('monobolki', 'Моноболки'), ('monitory', 'Мониторы')], max_length=300),
        ),
    ]