# Generated by Django 3.2.5 on 2021-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0022_auto_20210823_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('бытовые-техники', 'Бытовые-техники'), ('компьютерная-техника', 'Компьютерная-техника'), ('климатическая-техника', 'Климатическая-техника'), ('спортивные-товары', 'Спортивные-товары'), ('мужские-туфли', 'Мужские-туфли'), ('телефоны', 'Телефоны'), ('телевизоры', 'Телевизоры')], max_length=300)),
                ('subcategory', models.CharField(choices=[('xiaomi', 'ТелефоныXiaomi'), ('telSamsung', 'ТелефоныSamsung'), ('apple', 'ТелефоныApple'), ('samsung', 'ТелевизорыSamsung'), ('lg', 'ТелевизорыLg'), ('sony', 'ТелевизорыSony'), ('pylesosy', 'БытовыеТехникиПылесосы'), ('stiralki', 'БытовыеТехникиСтиральные машины'), ('xolodilniki', 'БытовыеТехникиХолодильники'), ('noutbuki', 'КомпьютерныеТехникиНоутбуки'), ('monobolki', 'КомпьютерныеТехникиМоноболки'), ('monitory', 'КомпьютерныеТехникиМониторы'), ('ventilyatory', 'КлиматическиеТехникиВентиляторы'), ('konditsionery', 'КлиматическиеТехникиКондиционеры'), ('obogrevateli', 'КлиматическиеТехникиОбогреватели')], max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bytovyetexniki',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='klimaticheskayatexnika',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='komputernayatexnika',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='mujskietufli',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sportivnyetovary',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tv',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('xiaomi', 'ТелефоныXiaomi'), ('telSamsung', 'ТелефоныSamsung'), ('apple', 'ТелефоныApple'), ('samsung', 'ТелевизорыSamsung'), ('lg', 'ТелевизорыLg'), ('sony', 'ТелевизорыSony'), ('pylesosy', 'БытовыеТехникиПылесосы'), ('stiralki', 'БытовыеТехникиСтиральные машины'), ('xolodilniki', 'БытовыеТехникиХолодильники'), ('noutbuki', 'КомпьютерныеТехникиНоутбуки'), ('monobolki', 'КомпьютерныеТехникиМоноболки'), ('monitory', 'КомпьютерныеТехникиМониторы'), ('ventilyatory', 'КлиматическиеТехникиВентиляторы'), ('konditsionery', 'КлиматическиеТехникиКондиционеры'), ('obogrevateli', 'КлиматическиеТехникиОбогреватели')], default=12, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BytovyeTexniki',
        ),
        migrations.DeleteModel(
            name='KlimaticheskayaTexnika',
        ),
        migrations.DeleteModel(
            name='KomputernayaTexnika',
        ),
        migrations.DeleteModel(
            name='MujskieTufli',
        ),
        migrations.DeleteModel(
            name='SportivnyeTovary',
        ),
        migrations.DeleteModel(
            name='Telefon',
        ),
        migrations.DeleteModel(
            name='Televizory',
        ),
    ]