# Generated by Django 3.2.5 on 2021-09-07 12:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0026_alter_order_tel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]