# Generated by Django 3.2.5 on 2021-09-10 06:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0027_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты'},
        ),
    ]