# Generated by Django 3.2.5 on 2021-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0029_auto_20210910_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('бытовые-техники', 'Бытовые-техники'), ('компьютерная-техника', 'Компьютерная-техника'), ('климатическая-техника', 'Климатическая-техника'), ('спортивные-товары', 'Спортивные-товары'), ('мужские-туфли', 'Мужские-туфли'), ('телефоны', 'Телефоны'), ('телевизоры', 'Телевизоры')], max_length=300, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='novinki',
            field=models.BooleanField(default=False, verbose_name='Новинки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularnye',
            field=models.BooleanField(default=False, verbose_name='Популарные'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]