# Generated by Django 3.2.5 on 2021-09-17 06:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0031_auto_20210910_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='order',
            name='imya',
        ),
    ]