# Generated by Django 3.2.5 on 2021-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0032_auto_20210917_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=12, max_length=5000, verbose_name='Описание:'),
            preserve_default=False,
        ),
    ]