# Generated by Django 3.2.5 on 2021-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0033_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Описание:'),
        ),
    ]