# Generated by Django 3.2.5 on 2021-09-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0034_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhoneModel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Screen size')),
            ],
            bases=('store.product',),
        ),
    ]