# Generated by Django 3.2.5 on 2021-09-26 06:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0035_smartphonemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartPhoneModel',
        ),
    ]