# Generated by Django 3.2.5 on 2021-09-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0036_delete_smartphonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('storage', models.CharField(max_length=300, verbose_name='Название продукта')),
            ],
            bases=('store.product',),
        ),
    ]