# Generated by Django 3.2.5 on 2021-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0038_auto_20210926_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]