# Generated by Django 3.2.5 on 2021-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0040_auto_20211014_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]