# Generated by Django 4.0.3 on 2022-03-19 19:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0049_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание:'),
        ),
    ]