# Generated by Django 4.0.3 on 2022-03-22 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('store', '0050_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заказанно'),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя:')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email:')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона:')),
                ('phoneAdd', models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп. номер телефона:')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес:')),
                ('time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время:')),
                ('date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дата:')),
                ('payment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Способ оплаты:')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Коментарии:')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Клиент')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='ID заказа')),
            ],
        ),
    ]